spring:
  cloud:
    vault:
      app-role:
        role-id: 90a001be-c1ed-7510-3dcd-4cb558787a40
        secret-id: ${SECRET_ID}
        app-role-path: approle
      authentication: approle
      uri: https://vault.infra-aws.com
    kv:
      backend: secret
      default-context: it-developer/ap-eosh/stage

  config:
    import: vault://it-developer/ap-eosh/stage
    activate:
      on-profile: stage

springdoc:
  default-support-form-data: true
  server-base-url: http://localhost:8088
  api-docs:
    enabled: true
    resolve-schema-properties: true
    groups:
      enabled: true
  swagger-ui:
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
    default-model-expand-depth: 5
    default-models-expand-depth: 5
    groups-order: ASC
    tags-sorter: alpha
    display-request-duration: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  show-login-endpoint: true
  cache:
    disabled: false
ecm:
  api:
    url: https://api-ecm.qa.flypremia.com
airpremia:
  api:
    url: https://api.flypremia.com
    x-api-key: T1PsxwSh7z1h87xNyu14GaJMUM4sBo2yvAjY9tGe
