debug: false
spring:
  profiles:
    active: local # default
  config:
    import:
      - classpath:/api-config.yaml
      - classpath:/com-airpremia-core-config.yaml
  transaction:
    rollback-on-commit-failure: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size:
        50010241024
      max-request-size:
        50010241024
server:
  port: 8088
  error:
    include-exception: true
    include-stacktrace: always
    path: '/error'
    whitelabel:
      enabled: true
mybatis:
  mapper-locations:
    - mapper/**/*.xml
    - mapper/**/**/*.xml
    - mapper/**/**/**/*.xml
    - mapper/**/**/**/**/*.xml
  type-aliases-package: com.airpremia.**
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    call-setters-on-nulls: true
    return-instance-for-empty-row: true
    cache-enabled: false
service:
  file-upload-root-path: /data/upload/file
  file-upload-servlet-path: /airpremia-meta/media
okta:
  oauth2:
    client-id: 0oahx8pqyitQKj3ke697
    client-secret: 0ibynuRvmlQP-KRH8FLgqMonOXEi7diVlVEkAPZW89K8jus_MvV38YIrYz9lGt6l
    authorization-grant-type: authorization_code
    redirect-uri: http://localhost:5173/api/auth/callback/okta
    scope: openid,profile,email
    authorization-uri: https://airpremia.okta.com/oauth2/v1/authorize
    token-uri: https://airpremia.okta.com/oauth2/v1/token
    user-info-uri: https://airpremia.okta.com/oauth2/v1/userinfo
    introspect-uri: https://airpremia.okta.com/oauth2/v1/introspect
management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, conditions, metrics
        exclude: threaddump, heapdump
