spring:
  cloud:
    vault:
      app-role:
        role-id: b9d52e48-d4e1-9c91-1080-ae3ff606f7c1
        secret-id: ${SECRET_ID}
        app-role-path: approle
      authentication: approle
      uri: https://vault.dev.infra-aws.com
    kv:
      backend: secret
      default-context: it-developer/ap-eosh/dev

  config:
    import: vault://it-developer/ap-eosh/dev
    activate:
      on-profile: dev

springdoc:
  default-support-form-data: true
  server-base-url: http://localhost:8088
  api-docs:
    enabled: true
    resolve-schema-properties: true
    groups:
      enabled: true
  swagger-ui:
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
    default-model-expand-depth: 5
    default-models-expand-depth: 5
    groups-order: ASC
    tags-sorter: alpha
    display-request-duration: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  show-login-endpoint: true
  cache:
    disabled: false
ecm:
  api:
    url: https://api-ecm.dev.flypremia.com
airpremia:
  api:
    url: https://api.dev.flypremia.com
    x-api-key: Wr0EyVfZKA6aFQNNz2TKHNbFtkUUbxP5Zz8EC794
