airpremia:
  core:
    security:
      jwt-secret: dd1225f7281c73ef80552d8db744498e922152101c41b51a04c1014dc318fa27aa21026203ae3972eaff80d5107f8db112fa436dda04c12f683258240d4ea73e3d9b6a79ff1751ae105229d788724cb8e1fe9aae02b60eefc9fd530318ab3ea41aa0dcd69e860bed56573d2fc2595b258f93daddabe0888dfd550552ca60caa89d990c1dae910087338ee28f3d7d887cff75b6218a2c6fd21ced32afdc13c341c6a90fa1ffb3a51f48146616a5ed3669f9e0a54aa9d843a01f49dbe6303bc97a4038d74866219e8a6700dad45e05b081ae311748d72b08747e346b11719ac117d0e16cb4fb0439ab45f1f0c86d1d51b77369ec46abb33f49ffb876748111df33
      jwt-access-token-expire-ms: 3600000
      jwt-refresh-token-expire-ms: 86400000
      token-refresh-uri: /auth/token/authorizeTokenRefresh
      jwt-not-check-uri-ant-matchers:
        - /auth/token/**
      permit-uri-ant-matchers:
        #       - /default/**
        #       - /sign/**
        #       - /init/**
        #       - /auth/token/**
        #       - /oauth/authorizeToken
        - /swagger-ui/**
        - /v3/api-docs/**
        - /**
      #      - /default/**
      #      - /authorizeToken
      cors:
        default-origin: http://localhost:3000
        white-list-origin:
          - http://localhost:5173
          - http://localhost:5174
          - https://eosh.dev.flypremia.com
          - https://eosh.qa.flypremia.com
          - https://eosh.stage.flypremia.com
          - https://eosh.flypremia.com
        methods: GET, POST, PUT, DELETE, PATCH
        headers: Authorization, Content-Type, xsrf-token, Authority, ZONEID
        expose-headers: xsrf-token, Authorization
        credentials: true
        max-age-second: 7200
    mybatis:
      logger-exclude-antpath-id:
      target-database-name: MARIA
