pipelines:
    branches:
        "**":
            - step:
                  name: "Clone (Branch)"
                  image: alpine/git:latest
                  script:
                      - export REPO_NAME="ap-eosh"
                      - git clone git@bitbucket.org:airpremia/$REPO_NAME.git
                      - cd $REPO_NAME
                      - git push --mirror git@github.com:airpremia/$REPO_NAME.git
                      - git checkout -b main origin/main
                      - git push --mirror git@github.com:airpremia/$REPO_NAME.git
    tags:
        "prod-releases/*":
            - step:
                  name: "Clone (Tag)"
                  script:
                      - export REPO_NAME="ap-eosh"
                      - git clone git@bitbucket.org:airpremia/$REPO_NAME.git
                      - cd $REPO_NAME
                      - git push --mirror git@github.com:airpremia/$REPO_NAME.git
                      - git checkout -b main origin/main
                      - git push --mirror git@github.com:airpremia/$REPO_NAME.git
